<?php

add_action( 'acf/init', function () {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    acf_add_local_field_group( [
        'key'    => 'group_place',
        'title'  => 'Miejsce – treść strony',
        'fields' => [

            // ── Hero ───────────────────────────────────────────────────────
            [
                'key'           => 'field_place_hero_title',
                'label'         => 'Hero – tytuł (HTML)',
                'name'          => 'hero_title',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Miejsce, które<br><b>wspiera proces</b>.',
            ],
            [
                'key'           => 'field_place_hero_btn_text',
                'label'         => 'Hero – tekst przycisku',
                'name'          => 'hero_btn_text',
                'type'          => 'text',
                'default_value' => 'Poznaj Obiekt',
            ],
            [
                'key'           => 'field_place_hero_btn_url',
                'label'         => 'Hero – URL przycisku',
                'name'          => 'hero_btn_url',
                'type'          => 'url',
                'default_value' => '#',
            ],
            [
                'key'           => 'field_place_hero_image_mobile',
                'label'         => 'Hero – grafika mobile',
                'name'          => 'hero_image_mobile',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Opcjonalna grafika na urządzeniach mobilnych (< 1024px). Jeśli puste, używana jest grafika główna.',
            ],

            // ── QORTY – oś czasu ───────────────────────────────────────────
            [
                'key'           => 'field_place_qorty_heading',
                'label'         => 'QORTY – nagłówek',
                'name'          => 'qorty_heading',
                'type'          => 'text',
                'default_value' => 'Budujemy przyszłość sportu',
            ],
            [
                'key'           => 'field_place_stage_1_label',
                'label'         => 'Etap 1 – etykieta',
                'name'          => 'stage_1_label',
                'type'          => 'text',
                'default_value' => 'I etap',
            ],
            [
                'key'           => 'field_place_stage_1_desc',
                'label'         => 'Etap 1 – opis',
                'name'          => 'stage_1_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Otwarcie 4 kortów ziemnych maj 2026',
            ],
            [
                'key'           => 'field_place_stage_2_label',
                'label'         => 'Etap 2 – etykieta',
                'name'          => 'stage_2_label',
                'type'          => 'text',
                'default_value' => 'II etap',
            ],
            [
                'key'           => 'field_place_stage_2_desc',
                'label'         => 'Etap 2 – opis',
                'name'          => 'stage_2_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Oddanie hali z 4 kortami hard wrzesień 2026',
            ],
            [
                'key'           => 'field_place_stage_3_label',
                'label'         => 'Etap 3 – etykieta',
                'name'          => 'stage_3_label',
                'type'          => 'text',
                'default_value' => 'III etap',
            ],
            [
                'key'           => 'field_place_stage_4_label',
                'label'         => 'Etap 4 – etykieta',
                'name'          => 'stage_4_label',
                'type'          => 'text',
                'default_value' => 'IV etap',
            ],
            [
                'key'           => 'field_place_stage_5_label',
                'label'         => 'Etap 5 – etykieta',
                'name'          => 'stage_5_label',
                'type'          => 'text',
                'default_value' => 'V etap',
            ],
            [
                'key'           => 'field_place_current_stage',
                'label'         => 'Aktualny etap',
                'name'          => 'current_stage',
                'type'          => 'number',
                'instructions'  => 'Numer etapu (1-5), na którym ma zatrzymać się pomarańczowa linia postępu.',
                'min'           => 1,
                'max'           => 5,
                'step'          => 1,
                'default_value' => 2,
            ],

            // ── Slider QORTY ───────────────────────────────────────────────
            [
                'key'           => 'field_place_qorty_slide_1',
                'label'         => 'Slider – zdjęcie 1',
                'name'          => 'qorty_slide_1',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_qorty_slide_2',
                'label'         => 'Slider – zdjęcie 2',
                'name'          => 'qorty_slide_2',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_qorty_slide_3',
                'label'         => 'Slider – zdjęcie 3',
                'name'          => 'qorty_slide_3',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_qorty_slide_4',
                'label'         => 'Slider – zdjęcie 4',
                'name'          => 'qorty_slide_4',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_qorty_slide_5',
                'label'         => 'Slider – zdjęcie 5',
                'name'          => 'qorty_slide_5',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],

            // ── Więcej niż ośrodek ─────────────────────────────────────────
            [
                'key'           => 'field_place_wiecej_heading',
                'label'         => '"Więcej niż" – nagłówek',
                'name'          => 'wiecej_heading',
                'type'          => 'text',
                'default_value' => 'Więcej niż ośrodek tenisowy',
            ],
            [
                'key'           => 'field_place_wiecej_text_1',
                'label'         => '"Więcej niż" – akapit 1',
                'name'          => 'wiecej_text_1',
                'type'          => 'wysiwyg',
                'toolbar'       => 'basic',
                'media_upload'  => 0,
                'default_value' => '<p>Powstający w Przeźmierowie pod Poznaniem kompleks QORT został zaprojektowany z myślą o jednym celu — stworzeniu środowiska, w którym każdy element infrastruktury wspiera rozwój zawodnika.</p>',
            ],
            [
                'key'           => 'field_place_wiecej_text_2',
                'label'         => '"Więcej niż" – akapit 2',
                'name'          => 'wiecej_text_2',
                'type'          => 'wysiwyg',
                'toolbar'       => 'basic',
                'media_upload'  => 0,
                'default_value' => '<p>Korty, przygotowanie motoryczne, regeneracja, diagnostyka i zaplecze medyczne funkcjonują w jednym ekosystemie. Dzięki temu proces treningowy nie kończy się po zejściu z kortu, lecz jest kontynuowany w każdym obszarze wpływającym na zdrowie i wynik sportowy.</p>',
            ],

            // ── Bloki statystyczne ─────────────────────────────────────────
            [
                'key'           => 'field_place_blok_1_value',
                'label'         => 'Blok 1 – wartość',
                'name'          => 'blok_1_value',
                'type'          => 'text',
                'default_value' => '4 500+ m²',
            ],
            [
                'key'           => 'field_place_blok_1_desc',
                'label'         => 'Blok 1 – opis',
                'name'          => 'blok_1_desc',
                'type'          => 'text',
                'default_value' => 'powierzchni sportowej i treningowej',
            ],
            [
                'key'           => 'field_place_blok_2_value',
                'label'         => 'Blok 2 – wartość',
                'name'          => 'blok_2_value',
                'type'          => 'text',
                'default_value' => 'Korty zewnętrzne',
            ],
            [
                'key'           => 'field_place_blok_2_desc',
                'label'         => 'Blok 2 – opis',
                'name'          => 'blok_2_desc',
                'type'          => 'text',
                'default_value' => 'przystosowane do treningu i rywalizacji',
            ],
            [
                'key'           => 'field_place_blok_3_value',
                'label'         => 'Blok 3 – wartość',
                'name'          => 'blok_3_value',
                'type'          => 'text',
                'default_value' => 'Całoroczna hala tenisowa',
            ],
            [
                'key'           => 'field_place_blok_3_desc',
                'label'         => 'Blok 3 – opis',
                'name'          => 'blok_3_desc',
                'type'          => 'text',
                'default_value' => 'wykonana w nowoczesnej technologii',
            ],
            [
                'key'           => 'field_place_blok_4_value',
                'label'         => 'Blok 4 – wartość',
                'name'          => 'blok_4_value',
                'type'          => 'text',
                'default_value' => 'Jedna lokalizacja',
            ],
            [
                'key'           => 'field_place_blok_4_desc',
                'label'         => 'Blok 4 – opis',
                'name'          => 'blok_4_desc',
                'type'          => 'text',
                'default_value' => 'łącząca trening, przygotowanie motoryczne i regenerację',
            ],

            // ── Infrastruktura ─────────────────────────────────────────────
            [
                'key'           => 'field_place_infra_heading',
                'label'         => 'Infrastruktura – nagłówek (HTML)',
                'name'          => 'infra_heading',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Kompleks zaprojektowany<br><b>wokół zawodnika</b>.',
            ],
            [
                'key'           => 'field_place_infra_1_image',
                'label'         => 'Infrastruktura 1 – zdjęcie',
                'name'          => 'infra_1_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_infra_1_heading',
                'label'         => 'Infrastruktura 1 – tytuł',
                'name'          => 'infra_1_heading',
                'type'          => 'text',
                'default_value' => 'Korty tenisowe',
            ],
            [
                'key'           => 'field_place_infra_1_desc',
                'label'         => 'Infrastruktura 1 – opis',
                'name'          => 'infra_1_desc',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => 'Sercem kompleksu są korty stanowiące podstawowe środowisko pracy zawodników QORT Tennis Academy. Infrastruktura została zaplanowana tak, aby umożliwiać realizację całorocznego procesu treningowego niezależnie od warunków atmosferycznych.',
            ],
            [
                'key'           => 'field_place_infra_2_image',
                'label'         => 'Infrastruktura 2 – zdjęcie',
                'name'          => 'infra_2_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_infra_2_heading',
                'label'         => 'Infrastruktura 2 – tytuł',
                'name'          => 'infra_2_heading',
                'type'          => 'text',
                'default_value' => 'Przygotowanie motoryczne',
            ],
            [
                'key'           => 'field_place_infra_2_desc',
                'label'         => 'Infrastruktura 2 – opis',
                'name'          => 'infra_2_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Dedykowane strefy treningowe pozwolą prowadzić rozwój siły, szybkości, mobilności i wytrzymałości w ścisłej integracji z planem tenisowym.',
            ],
            [
                'key'           => 'field_place_infra_3_image',
                'label'         => 'Infrastruktura 3 – zdjęcie',
                'name'          => 'infra_3_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_infra_3_heading',
                'label'         => 'Infrastruktura 3 – tytuł',
                'name'          => 'infra_3_heading',
                'type'          => 'text',
                'default_value' => 'Regeneracja i odnowa',
            ],
            [
                'key'           => 'field_place_infra_3_desc',
                'label'         => 'Infrastruktura 3 – opis',
                'name'          => 'infra_3_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Proces odbudowy organizmu jest nieodłącznym elementem sportu wyczynowego. Dlatego w kompleksie powstaje przestrzeń wspierająca regenerację po treningach i zawodach.',
            ],
            [
                'key'           => 'field_place_infra_4_image',
                'label'         => 'Infrastruktura 4 – zdjęcie',
                'name'          => 'infra_4_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_place_infra_4_heading',
                'label'         => 'Infrastruktura 4 – tytuł',
                'name'          => 'infra_4_heading',
                'type'          => 'text',
                'default_value' => 'Diagnostyka i opieka specjalistyczna',
            ],
            [
                'key'           => 'field_place_infra_4_desc',
                'label'         => 'Infrastruktura 4 – opis',
                'name'          => 'infra_4_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Zawodnicy będą mogli korzystać z wiedzy specjalistów oraz zaplecza medycznego wspierającego monitorowanie zdrowia i efektywności procesu treningowego.',
            ],
        ],
        'location' => [
            [
                [
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'template-pages/place.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'style'      => 'default',
    ] );
} );
