<?php

add_action( 'acf/init', function () {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    acf_add_local_field_group( [
        'key'    => 'group_homepage',
        'title'  => 'Homepage – treść strony',
        'fields' => [

            // ── Hero ───────────────────────────────────────────────────────
            [
                'key'           => 'field_hp_hero_title',
                'label'         => 'Hero – tytuł (HTML)',
                'name'          => 'hero_title',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => '<b>Najpierw zdrowie.</b><br>Potem wynik.',
            ],
            [
                'key'           => 'field_hp_hero_video',
                'label'         => 'Hero – wideo desktop',
                'name'          => 'hero_video_url',
                'type'          => 'file',
                'return_format' => 'url',
                'library'       => 'all',
                'mime_types'    => 'mp4,webm',
            ],
            [
                'key'           => 'field_hp_hero_video_poster',
                'label'         => 'Hero – wideo poster desktop (okładka)',
                'name'          => 'hero_video_poster',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_hero_video_mobile',
                'label'         => 'Hero – wideo mobile',
                'name'          => 'hero_video_mobile_url',
                'type'          => 'file',
                'return_format' => 'url',
                'library'       => 'all',
                'mime_types'    => 'mp4,webm',
            ],
            [
                'key'           => 'field_hp_hero_video_mobile_poster',
                'label'         => 'Hero – wideo mobile poster (nakładka)',
                'name'          => 'hero_video_mobile_poster',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_hero_btn_1_text',
                'label'         => 'Hero – przycisk 1 tekst',
                'name'          => 'hero_btn_1_text',
                'type'          => 'text',
                'default_value' => 'Poznaj Akademię',
            ],
            [
                'key'           => 'field_hp_hero_btn_1_url',
                'label'         => 'Hero – przycisk 1 URL',
                'name'          => 'hero_btn_1_url',
                'type'          => 'url',
                'default_value' => '#',
            ],
            [
                'key'           => 'field_hp_hero_btn_2_text',
                'label'         => 'Hero – przycisk 2 tekst',
                'name'          => 'hero_btn_2_text',
                'type'          => 'text',
                'default_value' => 'Skontaktuj się z nami',
            ],
            [
                'key'           => 'field_hp_hero_btn_2_url',
                'label'         => 'Hero – przycisk 2 URL',
                'name'          => 'hero_btn_2_url',
                'type'          => 'url',
                'default_value' => '#',
            ],

            // ── Liczby ─────────────────────────────────────────────────────
            [
                'key'           => 'field_hp_stat_1_value',
                'label'         => 'Liczby – stat 1 wartość',
                'name'          => 'stat_1_value',
                'type'          => 'text',
                'default_value' => '30',
            ],
            [
                'key'           => 'field_hp_stat_1_label',
                'label'         => 'Liczby – stat 1 opis',
                'name'          => 'stat_1_label',
                'type'          => 'text',
                'default_value' => 'Zawodników w programie',
            ],
            [
                'key'           => 'field_hp_stat_2_value',
                'label'         => 'Liczby – stat 2 wartość',
                'name'          => 'stat_2_value',
                'type'          => 'text',
                'default_value' => '5',
            ],
            [
                'key'           => 'field_hp_stat_2_label',
                'label'         => 'Liczby – stat 2 opis',
                'name'          => 'stat_2_label',
                'type'          => 'text',
                'default_value' => 'Filarów przygotowania',
            ],
            [
                'key'           => 'field_hp_stat_3_value',
                'label'         => 'Liczby – stat 3 wartość',
                'name'          => 'stat_3_value',
                'type'          => 'text',
                'default_value' => '24/7',
            ],
            [
                'key'           => 'field_hp_stat_3_label',
                'label'         => 'Liczby – stat 3 opis',
                'name'          => 'stat_3_label',
                'type'          => 'text',
                'default_value' => 'Opieka medyczna',
            ],
            [
                'key'           => 'field_hp_stat_4_value',
                'label'         => 'Liczby – stat 4 wartość',
                'name'          => 'stat_4_value',
                'type'          => 'text',
                'default_value' => '100%',
            ],
            [
                'key'           => 'field_hp_stat_4_label',
                'label'         => 'Liczby – stat 4 opis',
                'name'          => 'stat_4_label',
                'type'          => 'text',
                'default_value' => 'Indywidualne podejście',
            ],

            // ── Miejsce ────────────────────────────────────────────────────
            [
                'key'           => 'field_hp_miejsce_heading',
                'label'         => 'Miejsce – nagłówek (HTML)',
                'name'          => 'miejsce_heading',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Nowoczesne<br>centrum sportowe<br><b>w Przeźmierowie</b>',
            ],
            [
                'key'           => 'field_hp_miejsce_text_1',
                'label'         => 'Miejsce – akapit 1',
                'name'          => 'miejsce_text_1',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => 'Od 1,5 roku budujemy w Przeźmierowie pod Poznaniem nowoczesne centrum sportowe z kortami zewnętrznymi oraz całoroczną halą tenisową w najnowszej technologii.',
            ],
            [
                'key'           => 'field_hp_miejsce_text_2',
                'label'         => 'Miejsce – akapit 2',
                'name'          => 'miejsce_text_2',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Tworzymy kompleksowe zaplecze o powierzchni ponad 4 500 m², obejmujące strefy przygotowania motorycznego, fitness, siłownię oraz centrum regeneracji sportowej.',
            ],
            [
                'key'           => 'field_hp_miejsce_text_3',
                'label'         => 'Miejsce – akapit 3',
                'name'          => 'miejsce_text_3',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Równolegle rozwijamy infrastrukturę towarzyszącą – część hotelową i restauracyjną, sale konferencyjne i wykładowe oraz pełne zaplecze medyczne z diagnostyką i specjalistyczną opieką.',
            ],

            // ── Miejsce – zdjęcia ──────────────────────────────────────────
            [
                'key'           => 'field_hp_miejsce_image_1',
                'label'         => 'Miejsce – zdjęcie 1 (duże)',
                'name'          => 'miejsce_image_1',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_miejsce_image_2',
                'label'         => 'Miejsce – zdjęcie 2',
                'name'          => 'miejsce_image_2',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_miejsce_image_3',
                'label'         => 'Miejsce – zdjęcie 3',
                'name'          => 'miejsce_image_3',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_miejsce_image_4',
                'label'         => 'Miejsce – zdjęcie 4 (dolne prawe)',
                'name'          => 'miejsce_image_4',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],

            // ── Wizja ──────────────────────────────────────────────────────
            [
                'key'           => 'field_hp_wizja_heading',
                'label'         => 'Wizja – nagłówek',
                'name'          => 'wizja_heading',
                'type'          => 'text',
                'default_value' => 'Filozofia akademii',
            ],
            [
                'key'           => 'field_hp_wizja_intro',
                'label'         => 'Wizja – wstęp',
                'name'          => 'wizja_intro',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'W QORT Tennis Academy wierzymy, że prawdziwy sukces sportowy buduje się na fundamencie zdrowia i kompleksowego podejścia do rozwoju zawodnika.',
            ],
            [
                'key'           => 'field_hp_wizja_pillar_1_title',
                'label'         => 'Wizja filar 1 – tytuł',
                'name'          => 'wizja_pillar_1_title',
                'type'          => 'text',
                'default_value' => 'Zdrowie na pierwszym miejscu',
            ],
            [
                'key'           => 'field_hp_wizja_pillar_1_desc',
                'label'         => 'Wizja filar 1 – opis',
                'name'          => 'wizja_pillar_1_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Prewencja urazów i holistyczna opieka medyczna stanowią podstawę naszego programu.',
            ],
            [
                'key'           => 'field_hp_wizja_pillar_2_title',
                'label'         => 'Wizja filar 2 – tytuł',
                'name'          => 'wizja_pillar_2_title',
                'type'          => 'text',
                'default_value' => 'Selekcjonowany rozwój',
            ],
            [
                'key'           => 'field_hp_wizja_pillar_2_desc',
                'label'         => 'Wizja filar 2 – opis',
                'name'          => 'wizja_pillar_2_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Ograniczona liczba miejsc pozwala na prawdziwie indywidualne podejście do każdego zawodnika.',
            ],
            [
                'key'           => 'field_hp_wizja_pillar_3_title',
                'label'         => 'Wizja filar 3 – tytuł',
                'name'          => 'wizja_pillar_3_title',
                'type'          => 'text',
                'default_value' => 'Kompleksowość',
            ],
            [
                'key'           => 'field_hp_wizja_pillar_3_desc',
                'label'         => 'Wizja filar 3 – opis',
                'name'          => 'wizja_pillar_3_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Integracja wszystkich aspektów przygotowania – od techniki po psychikę.',
            ],

            // ── Wizja – media ──────────────────────────────────────────────
            [
                'key'           => 'field_hp_wizja_video',
                'label'         => 'Wizja – wideo URL',
                'name'          => 'wizja_video_url',
                'type'          => 'url',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_wizja_video_poster',
                'label'         => 'Wizja – wideo okładka (poster)',
                'name'          => 'wizja_video_poster',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_wizja_image_1',
                'label'         => 'Wizja – zdjęcie 1',
                'name'          => 'wizja_image_1',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_wizja_image_2',
                'label'         => 'Wizja – zdjęcie 2',
                'name'          => 'wizja_image_2',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],

            // ── Kadra ──────────────────────────────────────────────────────
            [
                'key'           => 'field_hp_kadra_heading',
                'label'         => 'Kadra – nagłówek',
                'name'          => 'kadra_heading',
                'type'          => 'text',
                'default_value' => 'Za każdym zawodnikiem stoi zespół',
            ],
            [
                'key'           => 'field_hp_kadra_intro',
                'label'         => 'Kadra – wstęp',
                'name'          => 'kadra_intro',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'W QORT Tennis Academy za rozwój zawodnika odpowiadają trenerzy, specjaliści zdrowia oraz eksperci wspierający przygotowanie fizyczne i mentalne. Wierzymy, że najlepsze wyniki są efektem współpracy całego zespołu.',
            ],

            // ── Opieka zdrowotna ───────────────────────────────────────────
            [
                'key'           => 'field_hp_opieka_heading',
                'label'         => 'Opieka – nagłówek (HTML)',
                'name'          => 'opieka_heading',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Zdrowie <b>jako fundament sukcesu</b>',
            ],
            [
                'key'           => 'field_hp_opieka_intro',
                'label'         => 'Opieka – wstęp',
                'name'          => 'opieka_intro',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'W QORT Tennis Academy opieka zdrowotna to nie dodatek – to absolutny priorytet. Nasza metodologia opiera się na trzech filarach.',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_1_title',
                'label'         => 'Opieka filar 1 – tytuł',
                'name'          => 'opieka_pillar_1_title',
                'type'          => 'text',
                'default_value' => 'Diagnostyka i profilaktyka',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_1_desc',
                'label'         => 'Opieka filar 1 – opis',
                'name'          => 'opieka_pillar_1_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Regularne badania i monitoring pozwalają wcześnie wykrywać ryzyko kontuzji i reagować, zanim się pojawią.',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_1_icon',
                'label'         => 'Opieka filar 1 – ikona SVG',
                'name'          => 'opieka_pillar_1_icon',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_2_title',
                'label'         => 'Opieka filar 2 – tytuł',
                'name'          => 'opieka_pillar_2_title',
                'type'          => 'text',
                'default_value' => 'Rehabilitacja i szybki powrót do gry',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_2_desc',
                'label'         => 'Opieka filar 2 – opis',
                'name'          => 'opieka_pillar_2_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Zespół fizjoterapeutów i osteopatów wspiera regenerację i pełny powrót do sprawności.',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_2_icon',
                'label'         => 'Opieka filar 2 – ikona SVG',
                'name'          => 'opieka_pillar_2_icon',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_3_title',
                'label'         => 'Opieka filar 3 – tytuł',
                'name'          => 'opieka_pillar_3_title',
                'type'          => 'text',
                'default_value' => 'Kompleksowa opieka',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_3_desc',
                'label'         => 'Opieka filar 3 – opis',
                'name'          => 'opieka_pillar_3_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Dietetyka, psychologia sportu i opieka medyczna tworzą spójny system troski o zawodnika.',
            ],
            [
                'key'           => 'field_hp_opieka_pillar_3_icon',
                'label'         => 'Opieka filar 3 – ikona SVG',
                'name'          => 'opieka_pillar_3_icon',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_opieka_image',
                'label'         => 'Opieka – zdjęcie',
                'name'          => 'opieka_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_hp_opieka_items',
                'label'         => 'Opieka – zakres (każda pozycja w nowej linii)',
                'name'          => 'opieka_items',
                'type'          => 'textarea',
                'rows'          => 6,
                'new_lines'     => '',
                'default_value' => "Badania diagnostyczne i screeningowe\nFizjoterapia i terapia manualna\nOsteopatia sportowa\nPoradnictwo dietetyczne\nMonitoring stanu zdrowia\nWsparcie w trakcie turniejów",
            ],

            // ── Rekrutacja – banner ────────────────────────────────────────
            [
                'key'           => 'field_hp_rekr_bg_image',
                'label'         => 'Rekrutacja – tło bannera',
                'name'          => 'rekrutacja_bg_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
            ],
            [
                'key'           => 'field_hp_rekr_banner_heading',
                'label'         => 'Rekrutacja – nagłówek bannera',
                'name'          => 'rekrutacja_banner_heading',
                'type'          => 'text',
                'default_value' => 'Opieka zdrowotna i rozwój zawodników',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text',
                'label'         => 'Rekrutacja – pozycja 1',
                'name'          => 'rekrutacja_banner_text',
                'type'          => 'text',
                'default_value' => 'Wsparcie medyczne, ortopedyczne',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_2',
                'label'         => 'Rekrutacja – pozycja 2',
                'name'          => 'rekrutacja_banner_text_2',
                'type'          => 'text',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_3',
                'label'         => 'Rekrutacja – pozycja 3',
                'name'          => 'rekrutacja_banner_text_3',
                'type'          => 'text',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_4',
                'label'         => 'Rekrutacja – pozycja 4',
                'name'          => 'rekrutacja_banner_text_4',
                'type'          => 'text',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_5',
                'label'         => 'Rekrutacja – pozycja 5',
                'name'          => 'rekrutacja_banner_text_5',
                'type'          => 'text',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_6',
                'label'         => 'Rekrutacja – pozycja 6',
                'name'          => 'rekrutacja_banner_text_6',
                'type'          => 'text',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_7',
                'label'         => 'Rekrutacja – pozycja 7',
                'name'          => 'rekrutacja_banner_text_7',
                'type'          => 'text',
                'default_value' => '',
            ],
            [
                'key'           => 'field_hp_rekr_banner_text_8',
                'label'         => 'Rekrutacja – pozycja 8',
                'name'          => 'rekrutacja_banner_text_8',
                'type'          => 'text',
                'default_value' => '',
            ],

            // ── Kontakt ────────────────────────────────────────────────────
            [
                'key'           => 'field_hp_kontakt_heading',
                'label'         => 'Kontakt – nagłówek (HTML)',
                'name'          => 'kontakt_heading',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Jeśli Cię zainteresowaliśmy, <br><b>napisz do nas</b>',
            ],
            [
                'key'           => 'field_hp_kontakt_intro',
                'label'         => 'Kontakt – wstęp',
                'name'          => 'kontakt_intro',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Skontaktujemy się z Tobą, aby omówić szczegóły i odpowiedzieć na pytania.',
            ],

            // ── Rekrutacja – kroki ─────────────────────────────────────────
            [
                'key'           => 'field_hp_rekr_heading',
                'label'         => 'Rekrutacja – nagłówek',
                'name'          => 'rekr_heading',
                'type'          => 'text',
                'default_value' => 'Proces rekrutacji',
            ],
            [
                'key'           => 'field_hp_rekr_intro',
                'label'         => 'Rekrutacja – wstęp',
                'name'          => 'rekr_intro',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Przyszłość sportu wyczynowego opiera się na integracji edukacji, zdrowia i treningu.',
            ],
            [
                'key'           => 'field_hp_rekr_step_1_num',
                'label'         => 'Krok 1 – numer',
                'name'          => 'rekr_step_1_num',
                'type'          => 'text',
                'default_value' => '01',
            ],
            [
                'key'           => 'field_hp_rekr_step_1_title',
                'label'         => 'Krok 1 – tytuł',
                'name'          => 'rekr_step_1_title',
                'type'          => 'text',
                'default_value' => 'Zgłoszenie',
            ],
            [
                'key'           => 'field_hp_rekr_step_1_desc',
                'label'         => 'Krok 1 – opis',
                'name'          => 'rekr_step_1_desc',
                'type'          => 'text',
                'default_value' => 'Wypełnienie formularza kontaktowego',
            ],
            [
                'key'           => 'field_hp_rekr_step_2_num',
                'label'         => 'Krok 2 – numer',
                'name'          => 'rekr_step_2_num',
                'type'          => 'text',
                'default_value' => '02',
            ],
            [
                'key'           => 'field_hp_rekr_step_2_title',
                'label'         => 'Krok 2 – tytuł',
                'name'          => 'rekr_step_2_title',
                'type'          => 'text',
                'default_value' => 'Rozmowa kwalifikacyjna',
            ],
            [
                'key'           => 'field_hp_rekr_step_2_desc',
                'label'         => 'Krok 2 – opis',
                'name'          => 'rekr_step_2_desc',
                'type'          => 'text',
                'default_value' => 'Poznanie zawodnika i jego celów',
            ],
            [
                'key'           => 'field_hp_rekr_step_3_num',
                'label'         => 'Krok 3 – numer',
                'name'          => 'rekr_step_3_num',
                'type'          => 'text',
                'default_value' => '03',
            ],
            [
                'key'           => 'field_hp_rekr_step_3_title',
                'label'         => 'Krok 3 – tytuł',
                'name'          => 'rekr_step_3_title',
                'type'          => 'text',
                'default_value' => 'Diagnostyka medyczna',
            ],
            [
                'key'           => 'field_hp_rekr_step_3_desc',
                'label'         => 'Krok 3 – opis',
                'name'          => 'rekr_step_3_desc',
                'type'          => 'text',
                'default_value' => 'Kompleksowe badania zdrowotne',
            ],
            [
                'key'           => 'field_hp_rekr_step_4_num',
                'label'         => 'Krok 4 – numer',
                'name'          => 'rekr_step_4_num',
                'type'          => 'text',
                'default_value' => '04',
            ],
            [
                'key'           => 'field_hp_rekr_step_4_title',
                'label'         => 'Krok 4 – tytuł',
                'name'          => 'rekr_step_4_title',
                'type'          => 'text',
                'default_value' => 'Ocena sportowa',
            ],
            [
                'key'           => 'field_hp_rekr_step_4_desc',
                'label'         => 'Krok 4 – opis',
                'name'          => 'rekr_step_4_desc',
                'type'          => 'text',
                'default_value' => 'Analiza umiejętności tenisowych',
            ],
            [
                'key'           => 'field_hp_rekr_step_5_num',
                'label'         => 'Krok 5 – numer',
                'name'          => 'rekr_step_5_num',
                'type'          => 'text',
                'default_value' => '05',
            ],
            [
                'key'           => 'field_hp_rekr_step_5_title',
                'label'         => 'Krok 5 – tytuł',
                'name'          => 'rekr_step_5_title',
                'type'          => 'text',
                'default_value' => 'Indywidualna oferta',
            ],
            [
                'key'           => 'field_hp_rekr_step_5_desc',
                'label'         => 'Krok 5 – opis',
                'name'          => 'rekr_step_5_desc',
                'type'          => 'text',
                'default_value' => 'Spersonalizowany program rozwoju',
            ],
            // ── Kolorystyka ────────────────────────────────────────────────
            [
                'key'   => 'field_hp_tab_colors',
                'label' => 'Kolorystyka strony',
                'name'  => '',
                'type'  => 'tab',
            ],
            [
                'key'           => 'field_hp_primary_color',
                'label'         => 'Kolor główny (akcentowy)',
                'name'          => 'site_primary_color',
                'type'          => 'color_picker',
                'default_value' => '',
            ],
        ],
        'location' => [
            [
                [
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'template-pages/homepage.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'style'      => 'default',
    ] );
} );
