<?php

add_action( 'acf/init', function () {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    acf_add_local_field_group( [
        'key'    => 'group_vision',
        'title'  => 'Wizja – treść strony',
        'fields' => [

            // ── Hero ───────────────────────────────────────────────────────
            [
                'key'           => 'field_vis_hero_title',
                'label'         => 'Hero – tytuł (HTML)',
                'name'          => 'hero_title',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Wynik to<br><b>efekt procesu</b>.',
            ],
            [
                'key'           => 'field_vis_hero_btn_text',
                'label'         => 'Hero – tekst przycisku',
                'name'          => 'hero_btn_text',
                'type'          => 'text',
                'default_value' => 'Poznaj Misję',
            ],
            [
                'key'           => 'field_vis_hero_btn_url',
                'label'         => 'Hero – URL przycisku',
                'name'          => 'hero_btn_url',
                'type'          => 'url',
                'default_value' => '#',
            ],
            [
                'key'           => 'field_vis_hero_image_mobile',
                'label'         => 'Hero – grafika mobile',
                'name'          => 'hero_image_mobile',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Opcjonalna grafika na urządzeniach mobilnych (< 1024px). Jeśli puste, używana jest grafika główna.',
            ],

            // ── Manifest ───────────────────────────────────────────────────
            [
                'key'           => 'field_vis_manifest_heading',
                'label'         => 'Manifest – nagłówek (HTML)',
                'name'          => 'manifest_heading',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Budujemy zawodników<br>zdolnych rozwijać się przez lata',
            ],
            [
                'key'           => 'field_vis_manifest_text_1',
                'label'         => 'Manifest – akapit 1',
                'name'          => 'manifest_text_1',
                'type'          => 'wysiwyg',
                'toolbar'       => 'basic',
                'media_upload'  => 0,
                'default_value' => '<p>QORT Tennis Academy powstała z przekonania, że rozwój zawodnika wymaga czegoś więcej niż dobrego treningu. Wymaga odpowiedniego otoczenia, zespołu specjalistów i konsekwentnie realizowanej strategii rozwoju.</p>',
            ],
            [
                'key'           => 'field_vis_manifest_text_2',
                'label'         => 'Manifest – akapit 2',
                'name'          => 'manifest_text_2',
                'type'          => 'wysiwyg',
                'toolbar'       => 'basic',
                'media_upload'  => 0,
                'default_value' => '<p>Dzisiaj o sukcesie nie decyduje wyłącznie jakość gry na korcie. Równie istotne są przygotowanie fizyczne, odporność mentalna, regeneracja, profilaktyka urazów oraz umiejętność funkcjonowania w wymagającym środowisku sportowym.</p>',
            ],
            [
                'key'           => 'field_vis_manifest_image',
                'label'         => 'Manifest – zdjęcie',
                'name'          => 'manifest_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],

            // ── 4 Filary ───────────────────────────────────────────────────
            [
                'key'           => 'field_vis_filary_heading',
                'label'         => 'Filary – nagłówek',
                'name'          => 'filary_heading',
                'type'          => 'text',
                'default_value' => '4 filary naszego podejścia',
            ],
            [
                'key'           => 'field_vis_filar_1_title',
                'label'         => 'Filar 1 – tytuł',
                'name'          => 'filar_1_title',
                'type'          => 'text',
                'default_value' => 'Długoterminowy rozwój',
            ],
            [
                'key'           => 'field_vis_filar_1_desc',
                'label'         => 'Filar 1 – opis',
                'name'          => 'filar_1_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Nie przygotowujemy zawodników na jeden sezon. Budujemy fundamenty, które pozwalają rozwijać się przez całą karierę sportową – od juniorów do seniorów.',
            ],
            [
                'key'           => 'field_vis_filar_1_image',
                'label'         => 'Filar 1 – zdjęcie',
                'name'          => 'filar_1_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_vis_filar_2_title',
                'label'         => 'Filar 2 – tytuł',
                'name'          => 'filar_2_title',
                'type'          => 'text',
                'default_value' => 'Indywidualne podejście',
            ],
            [
                'key'           => 'field_vis_filar_2_desc',
                'label'         => 'Filar 2 – opis',
                'name'          => 'filar_2_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Każdy zawodnik jest inny. Dlatego programy treningowe w QORT są tworzone z myślą o konkretnej osobie – jej mocnych stronach, ograniczeniach i celach.',
            ],
            [
                'key'           => 'field_vis_filar_2_image',
                'label'         => 'Filar 2 – zdjęcie',
                'name'          => 'filar_2_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_vis_filar_3_title',
                'label'         => 'Filar 3 – tytuł',
                'name'          => 'filar_3_title',
                'type'          => 'text',
                'default_value' => 'Holistyczne wsparcie',
            ],
            [
                'key'           => 'field_vis_filar_3_desc',
                'label'         => 'Filar 3 – opis',
                'name'          => 'filar_3_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Tenis to nie tylko uderzenia. W QORT łączymy trening techniczny z przygotowaniem motorycznym, opieką mentalną i regeneracją w jeden spójny system.',
            ],
            [
                'key'           => 'field_vis_filar_3_image',
                'label'         => 'Filar 3 – zdjęcie',
                'name'          => 'filar_3_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_vis_filar_4_title',
                'label'         => 'Filar 4 – tytuł',
                'name'          => 'filar_4_title',
                'type'          => 'text',
                'default_value' => 'Środowisko mistrzostwa',
            ],
            [
                'key'           => 'field_vis_filar_4_desc',
                'label'         => 'Filar 4 – opis',
                'name'          => 'filar_4_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Otoczenie kształtuje zawodnika. Kompleks QORT został zaprojektowany tak, by każdy element – od kortów po diagnostykę – służył jednemu celowi.',
            ],
            [
                'key'           => 'field_vis_filar_4_image',
                'label'         => 'Filar 4 – zdjęcie',
                'name'          => 'filar_4_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],

            // ── Spójny plan działania ──────────────────────────────────────
            [
                'key'           => 'field_vis_spojny_heading',
                'label'         => 'Plan działania – nagłówek',
                'name'          => 'spojny_heading',
                'type'          => 'text',
                'default_value' => 'Jeden zawodnik pełny system rozwoju',
            ],
            [
                'key'           => 'field_vis_spojny_subtitle',
                'label'         => 'Plan działania – podtytuł',
                'name'          => 'spojny_subtitle',
                'type'          => 'text',
                'default_value' => '8 obszarów, które wspólnie tworzą kompletną opiekę nad zawodnikiem',
            ],
            [
                'key'           => 'field_vis_spojny_image',
                'label'         => 'Plan działania – zdjęcie tła',
                'name'          => 'spojny_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_vis_spojny_image_mobile',
                'label'         => 'Plan działania – zdjęcie mobile',
                'name'          => 'spojny_image_mobile',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Opcjonalna grafika na urządzeniach mobilnych (< 1024px). Jeśli puste, używana jest grafika główna.',
            ],

            // ── Jak rozumiemy tenis ────────────────────────────────────────
            [
                'key'           => 'field_vis_tenis_heading',
                'label'         => 'Tenis – nagłówek',
                'name'          => 'tenis_heading',
                'type'          => 'text',
                'default_value' => 'Współczesny tenis',
            ],
            [
                'key'           => 'field_vis_tenis_text',
                'label'         => 'Tenis – treść',
                'name'          => 'tenis_text',
                'type'          => 'textarea',
                'rows'          => 6,
                'new_lines'     => '',
                'default_value' => 'Dzisiaj o sukcesie nie decyduje wyłącznie jakość gry na korcie. Równie istotne są przygotowanie fizyczne, odporność mentalna, regeneracja, profilaktyka urazów oraz umiejętność funkcjonowania w wymagającym środowisku sportowym.',
            ],

            // ── Program ────────────────────────────────────────────────────
            [
                'key'           => 'field_vis_program_heading',
                'label'         => 'Program – nagłówek',
                'name'          => 'program_heading',
                'type'          => 'text',
                'default_value' => 'Jednostki treningowe',
            ],
            [
                'key'           => 'field_vis_program_u10_label',
                'label'         => 'Program U10 – etykieta',
                'name'          => 'program_u10_label',
                'type'          => 'text',
                'default_value' => 'U10',
            ],
            [
                'key'           => 'field_vis_program_u10_units',
                'label'         => 'Program U10 – jednostki',
                'name'          => 'program_u10_units',
                'type'          => 'text',
                'default_value' => '30 jednostek miesięcznie',
            ],
            [
                'key'           => 'field_vis_program_u12_label',
                'label'         => 'Program U12 – etykieta',
                'name'          => 'program_u12_label',
                'type'          => 'text',
                'default_value' => 'U12',
            ],
            [
                'key'           => 'field_vis_program_u12_units',
                'label'         => 'Program U12 – jednostki',
                'name'          => 'program_u12_units',
                'type'          => 'text',
                'default_value' => '40 jednostek miesięcznie',
            ],
            [
                'key'           => 'field_vis_program_u14_label',
                'label'         => 'Program U14 – etykieta',
                'name'          => 'program_u14_label',
                'type'          => 'text',
                'default_value' => 'U14',
            ],
            [
                'key'           => 'field_vis_program_u14_units',
                'label'         => 'Program U14 – jednostki',
                'name'          => 'program_u14_units',
                'type'          => 'text',
                'default_value' => '52 jednostki miesięcznie',
            ],
            [
                'key'           => 'field_vis_program_u1618_label',
                'label'         => 'Program U16/U18 – etykieta',
                'name'          => 'program_u1618_label',
                'type'          => 'text',
                'default_value' => 'U16 i U18',
            ],
            [
                'key'           => 'field_vis_program_u1618_units',
                'label'         => 'Program U16/U18 – jednostki',
                'name'          => 'program_u1618_units',
                'type'          => 'text',
                'default_value' => '68 jednostek miesięcznie',
            ],
        ],
        'location' => [
            [
                [
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'template-pages/vision.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'style'      => 'default',
    ] );
} );
