<?php

add_action( 'acf/init', function () {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    acf_add_local_field_group( [
        'key'    => 'group_camp',
        'title'  => 'Camp – treść strony',
        'fields' => [

            // ── Hero ───────────────────────────────────────────────────────
            [
                'key'           => 'field_camp_hero_title',
                'label'         => 'Hero – tytuł (HTML)',
                'name'          => 'hero_title',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'High performance.<br><b>Tennis Camp</b>.',
            ],
            [
                'key'           => 'field_camp_hero_btn_text',
                'label'         => 'Hero – tekst przycisku',
                'name'          => 'hero_btn_text',
                'type'          => 'text',
                'default_value' => 'Dowiedz się więcej',
            ],
            [
                'key'           => 'field_camp_hero_btn_url',
                'label'         => 'Hero – URL przycisku',
                'name'          => 'hero_btn_url',
                'type'          => 'url',
                'default_value' => '#',
            ],
            [
                'key'           => 'field_camp_hero_image_mobile',
                'label'         => 'Hero – grafika mobile',
                'name'          => 'hero_image_mobile',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Opcjonalna grafika na urządzeniach mobilnych (< 1024px). Jeśli puste, używana jest grafika główna.',
            ],

            // ── Liczby ─────────────────────────────────────────────────────
            [
                'key'           => 'field_camp_stat_1_value',
                'label'         => 'Liczby – stat 1 wartość',
                'name'          => 'stat_1_value',
                'type'          => 'text',
                'default_value' => '3 dni',
            ],
            [
                'key'           => 'field_camp_stat_1_label',
                'label'         => 'Liczby – stat 1 opis',
                'name'          => 'stat_1_label',
                'type'          => 'text',
                'default_value' => 'Intensywny program',
            ],
            [
                'key'           => 'field_camp_stat_2_value',
                'label'         => 'Liczby – stat 2 wartość',
                'name'          => 'stat_2_value',
                'type'          => 'text',
                'default_value' => '2 terminy',
            ],
            [
                'key'           => 'field_camp_stat_2_label',
                'label'         => 'Liczby – stat 2 opis',
                'name'          => 'stat_2_label',
                'type'          => 'text',
                'default_value' => 'Wybierz dogodną datę',
            ],
            [
                'key'           => 'field_camp_stat_3_value',
                'label'         => 'Liczby – stat 3 wartość',
                'name'          => 'stat_3_value',
                'type'          => 'text',
                'default_value' => '2 300 zł',
            ],
            [
                'key'           => 'field_camp_stat_3_label',
                'label'         => 'Liczby – stat 3 opis',
                'name'          => 'stat_3_label',
                'type'          => 'text',
                'default_value' => 'Koszt campu',
            ],

            // ── Program campu ──────────────────────────────────────────────
            [
                'key'           => 'field_camp_program_intro',
                'label'         => 'Program – wstęp',
                'name'          => 'program_intro',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'W QORT Tennis Academy opieka zdrowotna to nie dodatek – to absolutny priorytet. Nasza metodologia opiera się na trzech filarach.',
            ],
            [
                'key'           => 'field_camp_pillar_1_title',
                'label'         => 'Filar 1 – tytuł',
                'name'          => 'pillar_1_title',
                'type'          => 'text',
                'default_value' => 'Zdrowie na pierwszym miejscu',
            ],
            [
                'key'           => 'field_camp_pillar_1_desc',
                'label'         => 'Filar 1 – opis',
                'name'          => 'pillar_1_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Prewencja urazów i holistyczna opieka medyczna stanowią podstawę naszego programu.',
            ],
            [
                'key'           => 'field_camp_pillar_1_icon',
                'label'         => 'Filar 1 – ikona SVG',
                'name'          => 'pillar_1_icon',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => '',
            ],
            [
                'key'           => 'field_camp_pillar_2_title',
                'label'         => 'Filar 2 – tytuł',
                'name'          => 'pillar_2_title',
                'type'          => 'text',
                'default_value' => 'Selekcjonowany rozwój',
            ],
            [
                'key'           => 'field_camp_pillar_2_desc',
                'label'         => 'Filar 2 – opis',
                'name'          => 'pillar_2_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Ograniczona liczba miejsc pozwala na prawdziwie indywidualne podejście do każdego zawodnika.',
            ],
            [
                'key'           => 'field_camp_pillar_2_icon',
                'label'         => 'Filar 2 – ikona SVG',
                'name'          => 'pillar_2_icon',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => '',
            ],
            [
                'key'           => 'field_camp_pillar_3_title',
                'label'         => 'Filar 3 – tytuł',
                'name'          => 'pillar_3_title',
                'type'          => 'text',
                'default_value' => 'Kompleksowość',
            ],
            [
                'key'           => 'field_camp_pillar_3_desc',
                'label'         => 'Filar 3 – opis',
                'name'          => 'pillar_3_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Integracja wszystkich aspektów przygotowania – od techniki po psychikę.',
            ],
            [
                'key'           => 'field_camp_pillar_3_icon',
                'label'         => 'Filar 3 – ikona SVG',
                'name'          => 'pillar_3_icon',
                'type'          => 'textarea',
                'rows'          => 4,
                'new_lines'     => '',
                'default_value' => '',
            ],

            // ── Program – zdjęcie i zakres medyczny ───────────────────────
            [
                'key'           => 'field_camp_program_image',
                'label'         => 'Program – zdjęcie (prawa kolumna)',
                'name'          => 'program_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_camp_med_section_heading',
                'label'         => 'Program – nagłówek zakresu medycznego',
                'name'          => 'med_section_heading',
                'type'          => 'text',
                'default_value' => 'Zakres opieki medycznej',
            ],
            [
                'key'           => 'field_camp_med_group_1_label',
                'label'         => 'Med. grupa 1 – nagłówek',
                'name'          => 'med_group_1_label',
                'type'          => 'text',
                'default_value' => 'Diagnostyka i badania',
            ],
            [
                'key'           => 'field_camp_med_group_1_items',
                'label'         => 'Med. grupa 1 – pozycje (każda w nowej linii)',
                'name'          => 'med_group_1_items',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => "Badania diagnostyczne i screeningowe\nMonitoring stanu zdrowia\nOcena wydolności i biomechaniki",
            ],
            [
                'key'           => 'field_camp_med_group_2_label',
                'label'         => 'Med. grupa 2 – nagłówek',
                'name'          => 'med_group_2_label',
                'type'          => 'text',
                'default_value' => 'Terapia i rehabilitacja',
            ],
            [
                'key'           => 'field_camp_med_group_2_items',
                'label'         => 'Med. grupa 2 – pozycje (każda w nowej linii)',
                'name'          => 'med_group_2_items',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => "Fizjoterapia i terapia manualna\nOsteopatia sportowa\nKinesiotaping i masaż sportowy",
            ],
            [
                'key'           => 'field_camp_med_group_3_label',
                'label'         => 'Med. grupa 3 – nagłówek',
                'name'          => 'med_group_3_label',
                'type'          => 'text',
                'default_value' => 'Wsparcie specjalistyczne',
            ],
            [
                'key'           => 'field_camp_med_group_3_items',
                'label'         => 'Med. grupa 3 – pozycje (każda w nowej linii)',
                'name'          => 'med_group_3_items',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => "Poradnictwo dietetyczne\nWsparcie w trakcie turniejów\nPrewencja urazów",
            ],

            // ── Kadra ──────────────────────────────────────────────────────
            [
                'key'           => 'field_camp_kadra_heading',
                'label'         => 'Kadra – nagłówek (HTML)',
                'name'          => 'kadra_heading',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Selekcjonowany<br><b>sztab specjalistów</b>',
            ],
            [
                'key'           => 'field_camp_kadra_intro',
                'label'         => 'Kadra – wstęp',
                'name'          => 'kadra_intro',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Cały program jest nadzorowany przez sztab szkoleniowy QORT Tennis Academy, który odpowiada za spójność metodyki, kontrolę procesu treningowego oraz utrzymanie najwyższych standardów szkolenia.',
            ],
            [
                'key'           => 'field_camp_camp_image_1',
                'label'         => 'Kadra – zdjęcie 1 (trenerzy)',
                'name'          => 'camp_image_1',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_camp_trenerzy_title',
                'label'         => 'Trenerzy – tytuł',
                'name'          => 'trenerzy_title',
                'type'          => 'text',
                'default_value' => 'Trenerzy tenisowi',
            ],
            [
                'key'           => 'field_camp_trenerzy_desc',
                'label'         => 'Trenerzy – opis',
                'name'          => 'trenerzy_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Doświadczeni szkoleniowcy z międzynarodowymi certyfikatami i udokumentowanymi sukcesami.',
            ],
            [
                'key'           => 'field_camp_trenerzy_tag',
                'label'         => 'Trenerzy – tag',
                'name'          => 'trenerzy_tag',
                'type'          => 'text',
                'default_value' => 'Indywidualne podejście do każdego zawodnika',
            ],
            [
                'key'           => 'field_camp_camp_image_2',
                'label'         => 'Kadra – zdjęcie 2 (kadra medyczna)',
                'name'          => 'camp_image_2',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_camp_medyczna_title',
                'label'         => 'Sztab medyczny – tytuł',
                'name'          => 'medyczna_title',
                'type'          => 'text',
                'default_value' => 'Sztab medyczny',
            ],
            [
                'key'           => 'field_camp_medyczna_desc',
                'label'         => 'Sztab medyczny – opis',
                'name'          => 'medyczna_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Fizjoterapeuci, osteopaci i lekarz sportowy zapewniają kompleksową opiekę.',
            ],
            [
                'key'           => 'field_camp_medyczna_tag',
                'label'         => 'Sztab medyczny – tag',
                'name'          => 'medyczna_tag',
                'type'          => 'text',
                'default_value' => 'Dostępność 24/7',
            ],
            [
                'key'           => 'field_camp_mentalne_title',
                'label'         => 'Wsparcie mentalne – tytuł',
                'name'          => 'mentalne_title',
                'type'          => 'text',
                'default_value' => 'Wsparcie mentalne',
            ],
            [
                'key'           => 'field_camp_mentalne_desc',
                'label'         => 'Wsparcie mentalne – opis',
                'name'          => 'mentalne_desc',
                'type'          => 'textarea',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Psychologowie sportowi pracują nad odpornością psychiczną i koncentracją.',
            ],
            [
                'key'           => 'field_camp_mentalne_tag',
                'label'         => 'Wsparcie mentalne – tag',
                'name'          => 'mentalne_tag',
                'type'          => 'text',
                'default_value' => 'Regularne sesje indywidualne',
            ],

            // ── Terminy ────────────────────────────────────────────────────
            [
                'key'           => 'field_camp_termin_1_label',
                'label'         => 'Termin 1 – etykieta',
                'name'          => 'termin_1_label',
                'type'          => 'text',
                'default_value' => 'Termin I',
            ],
            [
                'key'           => 'field_camp_termin_1_date',
                'label'         => 'Termin 1 – data',
                'name'          => 'termin_1_date',
                'type'          => 'text',
                'default_value' => '24–26.06.2026',
            ],
            [
                'key'           => 'field_camp_termin_2_label',
                'label'         => 'Termin 2 – etykieta',
                'name'          => 'termin_2_label',
                'type'          => 'text',
                'default_value' => 'Termin II',
            ],
            [
                'key'           => 'field_camp_termin_2_date',
                'label'         => 'Termin 2 – data',
                'name'          => 'termin_2_date',
                'type'          => 'text',
                'default_value' => '15–17.07.2026',
            ],
        ],
        'location' => [
            [
                [
                    'param'    => 'page_template',
                    'operator' => '==',
                    'value'    => 'template-pages/camp.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'style'      => 'default',
    ] );
} );
